# Generated by Django 4.1.1 on 2022-09-14 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_tukio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='planners',
            field=models.ManyToManyField(to='el_tukio.planner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vendors',
            field=models.ManyToManyField(to='el_tukio.vendor'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='bookmarks',
            field=models.ManyToManyField(related_name='organizer_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planner',
            name='bookmarks',
            field=models.ManyToManyField(related_name='planner_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
