# Generated by Django 4.1.1 on 2022-09-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_tukio', '0002_alter_event_planners_alter_event_vendors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
