# Generated by Django 4.1.1 on 2022-09-24 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el_tukio', '0004_alter_organizer_user_alter_planner_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_budget',
            field=models.FloatField(help_text='What  is the budget for this event?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='guest_size',
            field=models.IntegerField(help_text='Expected number of guests at the event?'),
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(help_text='Contract terms of agreement', max_length=5000)),
                ('date_sent', models.DateTimeField(auto_now_add=True, help_text='Time a contract is sent to the contractee')),
                ('date_signed', models.DateTimeField(help_text='Time the contractee signs the contract')),
                ('contractee', models.ForeignKey(help_text='Planner|Vendor receiving the contract', on_delete=django.db.models.deletion.CASCADE, related_name='contractee', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(help_text='Event Organizer|Planner giving the contract.', on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='el_tukio.event')),
            ],
        ),
    ]
