# Generated by Django 4.1.1 on 2022-09-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_tukio', '0006_alter_contract_date_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Declined')], default=0),
        ),
    ]
