# Generated by Django 4.1.1 on 2022-09-29 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el_tukio', '0009_task_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='el_tukio.event'),
        ),
    ]
