# Generated by Django 4.1.2 on 2022-11-07 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el_tukio', '0013_expense_date_deleted_expense_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='vendorcategory',
            options={'verbose_name': 'Vendor Category', 'verbose_name_plural': 'Vendor Categories'},
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'Personal'), (1, 'Group')])),
                ('members', models.ManyToManyField(related_name='chatroom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=5000)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='el_tukio.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='chatroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='el_tukio.chatroom'),
        ),
        migrations.CreateModel(
            name='ChatMessageReply',
            fields=[
                ('chatmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='el_tukio.chatmessage')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reply_message', to='el_tukio.chatmessage')),
            ],
            options={
                'verbose_name': 'Chat Message Reply',
                'verbose_name_plural': 'Chat Message Replies',
            },
            bases=('el_tukio.chatmessage',),
        ),
    ]
