# Generated by Django 4.1.2 on 2022-11-07 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_tukio', '0014_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='planners',
        ),
        migrations.RemoveField(
            model_name='event',
            name='vendors',
        ),
        migrations.AddField(
            model_name='event',
            name='event_team',
            field=models.ManyToManyField(related_name='event_team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
