# Generated by Django 4.1.2 on 2022-11-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_tukio', '0015_remove_event_planners_remove_event_vendors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(help_text='Enter message...', max_length=5000),
        ),
    ]
