# Generated by Django 4.1.2 on 2022-11-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_tukio', '0016_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='total_paid',
            field=models.FloatField(default=0, help_text='Total amount already paid for this budget item'),
        ),
    ]
