# Generated by Django 4.1.2 on 2022-11-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_tukio', '0017_alter_expense_total_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ChatMessageReply',
        ),
    ]
