# Generated by Django 4.1.2 on 2022-11-18 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_tukio', '0018_chatmessage_reply_to_delete_chatmessagereply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['date_sent']},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='terms',
        ),
        migrations.AddField(
            model_name='contract',
            name='comment',
            field=models.CharField(default=0, help_text='Any additional comment on the contract?', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='contract',
            field=models.FileField(default=0, help_text='Contract terms of agreement', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='chatroom', to=settings.AUTH_USER_MODEL),
        ),
    ]
