# Generated by Django 4.1.2 on 2022-11-19 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el_tukio', '0019_alter_chatmessage_options_remove_contract_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('fileupload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='el_tukio.fileupload')),
                ('title', models.SmallIntegerField(choices=[(1, 'Business permit or license')])),
            ],
            bases=('el_tukio.fileupload',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(help_text='Road/Street name', max_length=255)),
                ('neighbourhood', models.CharField(blank=True, help_text='Neighbourhood/Estate', max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('county', models.CharField(help_text='State/Province/County', max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.SmallIntegerField(blank=True, choices=[(None, '(Unkown)'), (0, 'Organizer'), (1, 'Planner'), (3, 'Vendor')], null=True),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('docs', models.ManyToManyField(to='el_tukio.legaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='el_tukio.location'),
        ),
    ]
